name: 'Upgrade Provider Repositories'

on:
  workflowDispatch: {}

jobs:
  terraform:
    name: 'Upgrade'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: hashicorp/cdktf-provider-null
    - run: yarn add --dev @cdktf/provider-project@latest projen@latest