name: 'Upgrade Provider Repositories'

on:
  workflow_dispatch: {}

jobs:
  terraform:
    name: 'Upgrade'
    runs-on: ubuntu-latest
    container:
      image: hashicorp/jsii-terraform
    strategy:
      matrix:
        provider:
          # - "aws"
          # - "google"
          # - "azurerm"
          # - "null"
          # - "kubernetes"
          - "docker"
          # - "github"
          # - "external"
          # - "datadog"
          # - "random"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: hashicorp/cdktf-provider-${{ matrix.provider }}
        token: ${{ secrets.GH_COMMENT_TOKEN }}
        path: provider
    - uses: actions/github-script@v4
      with:
        script: |
          const path = require('path')
          const fs = require('fs')
          const provider = require('./main/provider.json')
          const providerVersion = provider["${{ matrix.provider }}"]
          const template = fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, 'main', 'projenrc.template.js'), 'utf-8')
          const projenrc = template.replace('__PROVIDER__', providerVersion)
          fs.writeFileSync(path.join(process.env.GITHUB_WORKSPACE, 'provider', '.projenrc.js'), projenrc)
    - name: Upgrade provider project
      run: |
        unset CI
        git config user.name github-team-tf-cdk
        git config user.email github-team-tf-cdk@hashicorp.com
        git checkout -b foo-bar-${{ github.run_number }}
        yarn add --dev @cdktf/provider-project@latest projen
        npx projen
        yarn install --check-files
        npx projen
      working-directory: ./provider
    - name: Check for changes
      id: git_diff
      run: |
        git diff --exit-code || echo "::set-output name=has_changes::true"
      working-directory: ./provider
    - if: steps.git_diff.outputs.has_changes
      name: Commit and push changes (if changed)
      run: |
        git checkout -b upgrade-provider-project-${{ github.run_number }}
        git add .
        git commit -m "chore: upgrade provider-project and projen"
        git push --set-upstream origin upgrade-provider-project-${{ github.run_number }}
      working-directory: ./provider
    - if: steps.git_diff.outputs.has_changes
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GH_COMMENT_TOKEN }}
        script: |
          const { GITHUB_SERVER_URL, GITHUB_REPOSITORY, GITHUB_RUN_ID } = process.env
          const url = `${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}`
          github.pulls.create({
            owner: "hashicorp",
            repo: "cdktf-provider-${{ matrix.provider }}",
            head: "upgrade-provider-project-${{ github.run_number }}",
            base: "main",
            title: "Upgrade provider project and projen",
            maintainer_can_modify: true,
            body: `Triggered by ${url}`
          })